name: rtsp_streamer
description: "A new Flutter project to stream video."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    image_path: "assets/cofee.png"

flutter:

  uses-material-design: true
